### ISSUE TITLE
Buttons 'go faster' and 'go slower' drive the application to crash.

### ISSUE THREAD

**Issue by bsaid** [bsaid/ElevatorSimulator#6]
When the simulation is running and the user pushes 'go faster' or 'go slower' button, the whole simulator crashes.

**Comment by redsti-github** [comment]
i've not managed to replicate this behaviour, could you elaborate more how this happens? does it crash after pressing the button once or only when it's at very high/slow speeds?

**Comment by bsaid** [comment]
Start `example.py`, then click the `play` button, then click `go faster`. Then, it crashes with this message:

```
Traceback (most recent call last):
  File "/Users/bes/Desktop/REPO/ElevatorSimulator/elevators.py", line 388, in speedUpTime
    self.timer.setInterval(100 / self.timeScale)
TypeError: setInterval(self, msec: int): argument 1 has unexpected type 'float'
zsh: abort      /opt/homebrew/bin/python3.11 
```

**Comment by redsti-github** [comment]
I didn't encounter this error before since i was using python 3.9, so after i downloaded python 3.11 i managed to replicate the bug. Pull request #9 should fix it.

**Comment by bsaid** [comment]
Great, thank you. This is exactly the reason why it is always necessary to provide all information about the bug including the versions of the used tools. (description of the bug, how to replicate it, the used OS or HW, versions of all used tools, any other related information)
